package com.excel.service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.excel.bean.ProductMasterBean;
import com.excel.bean.Prod_MasterBean;
import com.excel.bean.UploadMsrAllocBean;
import com.excel.model.Alloc_Detail;
import com.excel.model.Alloc_Remark;
import com.excel.model.Alloc_Temp;
import com.excel.model.Alloc_Temp_Header;
import com.excel.model.Alloc_gen_dt;
import com.excel.model.Am_m_System_Parameter;
import com.excel.model.FieldStaff;
import com.excel.model.Msr_Stock;
import com.excel.model.Period;
import com.excel.model.SmpItem;
import com.excel.repository.AllocDetailRepository;
import com.excel.repository.AllocTempRepository;
import com.excel.repository.FieldStaffRepository;
import com.excel.repository.MsrStockRepository;
import com.excel.repository.PeriodMasterRepository;
import com.excel.repository.ProductMasterRepository;
import com.excel.repository.TransactionalRepository;
import com.excel.utility.MedicoResources;

@Service
public class AllocTempServiceImpl implements AllocTempService {
	
	@Autowired TransactionalRepository transactionalRepository;
	@Autowired PeriodMasterRepository periodMasterRepository;
	@Autowired FieldStaffRepository fieldStaffRepository;
	@Autowired ProductMasterRepository productMasterRepository;
	@Autowired MsrStockRepository msrStockRepository;
	@Autowired AllocDetailRepository allocDetailRepository;
	@Autowired AllocTempRepository allocTempRepository;
	
	@Override
	@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
   public void saveUploadData(List<UploadMsrAllocBean> msr_Allocs,String includestock,String team_code)
				throws Exception {

			boolean flag=true;
			Alloc_Temp_Header alloc_Temp_Header=null;
			
			try {
				System.out.println("msr_Allocs "+msr_Allocs.size());
				
				for (UploadMsrAllocBean msr_Alloc : msr_Allocs) {
					for (Prod_MasterBean products_Alloc : msr_Alloc.getProduct_Masters()) {
						System.out.println("msr_Alloc "+msr_Alloc.getProduct_Masters());
						if(flag){
							alloc_Temp_Header=new Alloc_Temp_Header();
							alloc_Temp_Header.setInput_type(msr_Alloc.getInput_type());
							alloc_Temp_Header.setAlloc_type(msr_Alloc.getUpload_status());//Monthly or additional in case of header
							alloc_Temp_Header.setApp_acquired(0);
							alloc_Temp_Header.setApp_required(msr_Alloc.getLevel());
							alloc_Temp_Header.setApproval_remark("");
							alloc_Temp_Header.setApproval_status('N');
							alloc_Temp_Header.setCompany(msr_Alloc.getCompany());
							alloc_Temp_Header.setCsv_file_name(msr_Alloc.getFileUploadFileName());
							String file_name=msr_Alloc.getFileUploadFileName();
							int index=file_name.lastIndexOf("_");
							if(index > 0){
								String u_status=String.valueOf(msr_Alloc.getUpload_status());
								System.out.println("Header Id "+msr_Alloc.getAlloc_header_id() +" u_status"+ u_status);
								if(u_status.equals("A") || u_status.equals("M") ){
									alloc_Temp_Header.setUpload_type("S");//Directly from alloc gen, Uploaded CSV generated by Alloc Gen, Manual
									alloc_Temp_Header.setAlloc_header_id(Long.valueOf(msr_Alloc.getAlloc_header_id()));
									alloc_Temp_Header.setAlloc_xgenheader_id(0L);
								}else{
									alloc_Temp_Header.setUpload_type("X");
									alloc_Temp_Header.setAlloc_header_id(0L);
									alloc_Temp_Header.setAlloc_xgenheader_id(Long.valueOf(msr_Alloc.getAlloc_xgen_header_id()));
								}
							}else{
								alloc_Temp_Header.setUpload_type("M");
								alloc_Temp_Header.setAlloc_header_id(0L);
								alloc_Temp_Header.setAlloc_xgenheader_id(0L);
							}
							alloc_Temp_Header.setCycle(msr_Alloc.getCycle());
							alloc_Temp_Header.setDiv_id(msr_Alloc.getDivision());					
							alloc_Temp_Header.setFin_year(msr_Alloc.getYear());
							alloc_Temp_Header.setIns_ip_add(msr_Alloc.getCreated_by_ip());					
							alloc_Temp_Header.setIns_usr_id(msr_Alloc.getCreated_by());
							alloc_Temp_Header.setPeriod_code(msr_Alloc.getPeriod());
							alloc_Temp_Header.setUpload_cycle(msr_Alloc.getUpload_cycle());
							alloc_Temp_Header.setTeam_code(team_code);
							alloc_Temp_Header.setTeam_code(team_code);
							if(msr_Alloc.getSrtno()== null || msr_Alloc.getSrtno().equals("")) {
								alloc_Temp_Header.setSrt_number(" ");
							}else {alloc_Temp_Header.setSrt_number(msr_Alloc.getSrtno());}
							if(msr_Alloc.getSrtdate() == null || msr_Alloc.getSrtdate().equals("")) {
								alloc_Temp_Header.setSrt_date(null);
							}else {
								if (msr_Alloc.getSrtdate().trim().length() > 0) {
									 if(msr_Alloc.getSrtdate().trim().contains("-")) {
										 msr_Alloc.setSrtdate(msr_Alloc.getSrtdate().replace("-", "/"));
									 }
								}

								alloc_Temp_Header.setSrt_date(MedicoResources.convert_DD_MM_YYYY_toDate(msr_Alloc.getSrtdate()));
							}
							if(msr_Alloc.getSrtremark()==null || msr_Alloc.getSrtremark().equals("")) {
								alloc_Temp_Header.setSrt_remark(" ");
							}else {alloc_Temp_Header.setSrt_remark(msr_Alloc.getSrtremark());}
							
							this.transactionalRepository.persist(alloc_Temp_Header);
							flag=false;
						}
						
						Alloc_Temp alloc_Temp = new Alloc_Temp();
						alloc_Temp.setAlloc_Temp_Header(alloc_Temp_Header);
						alloc_Temp.setCsv_file_name(msr_Alloc.getFileUploadFileName());
						alloc_Temp.setAlloc_header_id(Long.valueOf(msr_Alloc.getAlloc_header_id()));
						alloc_Temp.setFin_year_id(msr_Alloc.getYear());
						alloc_Temp.setCompany(msr_Alloc.getCompany());
						alloc_Temp.setPeriod_code(msr_Alloc.getPeriod());
						alloc_Temp.setFscode(msr_Alloc.getFs_code());
						alloc_Temp.setFsname(msr_Alloc.getFs_name());
						alloc_Temp.setFstaff_id(msr_Alloc.getFstaff_id());
						alloc_Temp.setDiv_id(msr_Alloc.getDivision());
						alloc_Temp.setAlloc_type("");
						alloc_Temp.setCycle(msr_Alloc.getCycle());
						alloc_Temp.setUpload_cycle(msr_Alloc.getUpload_cycle());
						alloc_Temp.setIns_usr_id(msr_Alloc.getCreated_by());
						alloc_Temp.setIns_ip_add(msr_Alloc.getCreated_by_ip());
						alloc_Temp.setStatus('A');
						alloc_Temp.setUpload_status(msr_Alloc.getUpload_status());//Monthly or additional in case of detail
						System.out.println("Upload Status "+msr_Alloc.getUpload_status());
						alloc_Temp.setProd_id(products_Alloc.getProduct_id());
						alloc_Temp.setProd_code(products_Alloc.getProduct_code());
						alloc_Temp.setAlloc_qty(new BigDecimal(products_Alloc.getProduct_qty()));
						alloc_Temp.setRate(products_Alloc.getProduct_rate());
						alloc_Temp.setAlt_div_id(products_Alloc.getAlt_div_id());
						alloc_Temp.setInv_grp(products_Alloc.getInv_grp());
						alloc_Temp.setProd_name(products_Alloc.getProduct_name());
						alloc_Temp.setTeam_code(msr_Alloc.getTeam_code());
						BigDecimal qty = alloc_Temp.getAlloc_qty();
						
						alloc_Temp.setMsr_stock(new BigDecimal(0));
						if(includestock.equalsIgnoreCase("Y")){
							Period master=periodMasterRepository.getPreviousPeriod();
							
							Period allcdtl_master=periodMasterRepository.getPreviousPeriod(msr_Alloc.getPeriod(),msr_Alloc.getYear());
							
							
							Alloc_Detail alloc_Detail=this.allocDetailRepository.getAlloc_DetailObj( msr_Alloc.getDivision(),allcdtl_master.getPeriod_code(), msr_Alloc.getCompany(), allcdtl_master.getPeriod_fin_year().toString(), msr_Alloc.getFstaff_id(), products_Alloc.getProduct_id(),
									String.valueOf(msr_Alloc.getUpload_status()));
							
							Msr_Stock msr_Stock = this.msrStockRepository.getMsr_StockObj(
									alloc_Temp.getFstaff_id(),
									master.getPeriod_code(),
									alloc_Temp.getProd_id(),
									master.getPeriod_fin_year().toString());
							//BigDecimal qty = alloc_Temp.getAlloc_qty();
							if (msr_Stock != null) {
								alloc_Temp.setMsr_stock(msr_Stock.getClstock());
								qty = qty.subtract(alloc_Temp.getMsr_stock());
								if(alloc_Detail!=null){
									qty=qty.add(alloc_Detail.getAllocdtl_curr_alloc_qty());
								}
							} else {
								alloc_Temp.setMsr_stock(new BigDecimal(0));// initial
																			// value
							}
							
						}	
							BigDecimal final_qty = (qty.divide(products_Alloc.getMin_alloc_qty(), 0,RoundingMode.CEILING)).multiply(products_Alloc.getMin_alloc_qty());
							alloc_Temp.setFinal_allocqty(final_qty);
						
						this.transactionalRepository.persist(alloc_Temp);
					}

				}
			} catch (Exception e) {
				throw e;
			} finally {
			}
		}

   @Override
   @Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
   public void saveAlloc_Gen_data(List<Alloc_gen_dt> alloc_gen_dts,char alloc_mode,Long upload_cycle,String ipAddress,int level,String userid)throws Exception {
		boolean flag=true;
		Alloc_Temp_Header alloc_Temp_Header=null;
		try {

			///Am_m_System_Parameter param = paramDao.getSpValueBySpName("Alloc_APPR_REQ");
			//Integer appr_req = Integer.parseInt(param.getSp_value());
			Integer appr_req=1;
			for (Alloc_gen_dt gen_dt : alloc_gen_dts) {
				if(flag){
					alloc_Temp_Header=new Alloc_Temp_Header();
					alloc_Temp_Header.setInput_type(Integer.valueOf(gen_dt.getAlloc_gen_id().getInputType()));
					alloc_Temp_Header.setAlloc_header_id(Long.valueOf(gen_dt.getAlloc_gen_id().getAlloc_gen_id()));
					alloc_Temp_Header.setAlloc_type(alloc_mode);//Monthly or additional in case of header
					alloc_Temp_Header.setAlloc_xgenheader_id(0L);
					alloc_Temp_Header.setApp_acquired(0);
					alloc_Temp_Header.setApp_required(appr_req);
					alloc_Temp_Header.setApproval_remark("");
					alloc_Temp_Header.setApproval_status('N');
					alloc_Temp_Header.setCompany(gen_dt.getCompany());
					alloc_Temp_Header.setCycle(gen_dt.getAlloc_cycle().intValue());
					alloc_Temp_Header.setDiv_id(gen_dt.getDiv_id());					
					alloc_Temp_Header.setFin_year(Long.valueOf(gen_dt.getFin_year()));
					alloc_Temp_Header.setIns_ip_add(ipAddress);					
					alloc_Temp_Header.setIns_usr_id(userid);
					alloc_Temp_Header.setPeriod_code(gen_dt.getPeriod_code());
					alloc_Temp_Header.setUpload_cycle(Integer.valueOf(gen_dt.getAlloc_cycle().toString()));
					alloc_Temp_Header.setUpload_type("D");//Directly from alloc gen, Uploaded CSV generated by Alloc Gen, Manual
					this.transactionalRepository.persist(alloc_Temp_Header);
					flag=false;
				}
				
				
				
				Alloc_Temp alloc_Temp = new Alloc_Temp();
				alloc_Temp.setAlloc_Temp_Header(alloc_Temp_Header);
				alloc_Temp.setAlloc_header_id(gen_dt.getAlloc_gen_id().getAlloc_gen_id());
				alloc_Temp.setFin_year_id(Long.valueOf(gen_dt.getFin_year()));
				alloc_Temp.setCompany(gen_dt.getCompany());
				alloc_Temp.setPeriod_code(gen_dt.getPeriod_code());
				alloc_Temp.setDiv_id(gen_dt.getDiv_id());
				alloc_Temp.setAlloc_type("");
				alloc_Temp.setCycle(gen_dt.getAlloc_cycle().intValue());
				alloc_Temp.setIns_usr_id(gen_dt.getUser_id());
				alloc_Temp.setIns_ip_add(ipAddress);
				alloc_Temp.setStatus('A');
				alloc_Temp.setUpload_status(alloc_mode);
				alloc_Temp.setUpload_cycle(Integer.valueOf(gen_dt.getAlloc_cycle().toString()));
				
				FieldStaff field_Staff = null;
				BigDecimal qty = null;
				if (gen_dt.getRbm_id() != null
						&& gen_dt.getRbm_id().longValue() > 0) {
					field_Staff = this.fieldStaffRepository.getObjectByStaffId(gen_dt.getRbm_id());
					qty = new BigDecimal(gen_dt.getAlloc_qty_rbm());
				} else if (gen_dt.getAbm_id() != null
						&& gen_dt.getAbm_id().longValue() > 0) {
					field_Staff = this.fieldStaffRepository.getObjectByStaffId(gen_dt.getAbm_id());
					qty = new BigDecimal(gen_dt.getAlloc_qty_abm());
				} else if (gen_dt.getMsr_id() != null
						&& gen_dt.getMsr_id().longValue() > 0) {
					field_Staff = this.fieldStaffRepository.getObjectByStaffId(gen_dt.getMsr_id());
					qty = new BigDecimal(gen_dt.getAlloc_qty_msr());
				}
				if (field_Staff != null) {
					alloc_Temp.setFscode(field_Staff.getFstaff_map_code1());
					alloc_Temp.setFsname(field_Staff.getFstaff_display_name());
					alloc_Temp.setFstaff_id(field_Staff.getFstaff_id());
					alloc_Temp.setAlloc_qty(qty);
				}
				SmpItem item = this.productMasterRepository.getObjectById(gen_dt.getProd_id());

				alloc_Temp.setProd_id(item.getSmp_prod_id());
				alloc_Temp.setProd_code(item.getSmp_prod_cd());

				alloc_Temp.setRate(item.getSmp_rate());
				alloc_Temp.setAlt_div_id(item.getSmp_std_div_id());
				alloc_Temp.setInv_grp(item.getInv_grp_id());
				alloc_Temp.setProd_name(item.getSmp_prod_name());

				alloc_Temp.setMsr_stock(new BigDecimal(0));

				BigDecimal final_qty = (qty.divide(item.getMin_alloc_qty(), 0,
						RoundingMode.CEILING))
						.multiply(item.getMin_alloc_qty());
				alloc_Temp.setFinal_allocqty(final_qty);

				this.transactionalRepository.persist(alloc_Temp);

			}
		} catch (Exception e) {
			throw e;
		}

	}
   
	   @Override
	   @Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
	   public void updateApprovalStatus(Long alloc_temp_hd_id,String status)throws Exception {
		   System.out.println("status "+status+" alloc_temp_hd_id"+alloc_temp_hd_id);
		   Alloc_Temp_Header header=this.allocTempRepository.getObjectAllocTempHeader(alloc_temp_hd_id);
		   header.setApproval_status(status.charAt(0));
		   this.transactionalRepository.update(header);
	   }

	@Override
	public void saveAllocationRemark(String Remark, Long alloctemp_id) throws Exception {
		// TODO Auto-generated method stub
		try {
			 Alloc_Temp_Header header=this.allocTempRepository.getObjectAllocTempHeader(alloctemp_id);
			Alloc_Remark remark = new Alloc_Remark();
			remark.setAlloc_id(0l);
			remark.setAlloc_gen_hd_id(header.getAlloc_header_id());
			remark.setAlloc_remark(Remark);
			this.transactionalRepository.persist(remark);
		}
		catch (Exception e) {
			// TODO: handle exception
			throw e;
		}
	}

	@Override
	public void updateApprovalStatusWithRemark(Long alloc_temp_hd_id, String status, String remark) throws Exception {
		  System.out.println("status "+status+" alloc_temp_hd_id"+alloc_temp_hd_id);
		   Alloc_Temp_Header header=this.allocTempRepository.getObjectAllocTempHeader(alloc_temp_hd_id);
		   header.setApproval_status(status.charAt(0));
		   header.setApproval_remark(remark);
		   this.transactionalRepository.update(header);

	}

	}

